WIP: firefox: backport some changes to fix build with newer rust
* cssparser fails to build with:
  error[E0425]: cannot find value `MAX_LENGTH` in this scope
  error[E0425]: cannot find value `MAP` in this scope
  as shown in:
  http://errors.yoctoproject.org/Errors/Details/731831/

  which leads to
  https://github.com/rust-lang/rust/issues/76480
  https://bugzilla.mozilla.org/show_bug.cgi?id=1663677

* but this still isn't enough to build firefox with current rust 1.71.0 in oe-core
  I've tried to backport multiple changes like:
  https://bugzilla.mozilla.org/show_bug.cgi?id=1663715#c5
  https://hg.mozilla.org/releases/mozilla-esr78/rev/5db8c1e9f643ec26fc93e7a3fc7a90c742b11030
  https://hg.mozilla.org/releases/mozilla-esr78/rev/6445a3a0e81d6aeeaa976be784edf2de9fab84de
  https://hg.mozilla.org/mozilla-central/rev/e2cede25c027
  https://phabricator.services.mozilla.com/D89473
  https://hg.mozilla.org/mozilla-central/rev/da77d5528a08
  https://phabricator.services.mozilla.com/D83816

* but it's neverending story of more and more fixes and esr68 is just
  too old and not worth spending more time on it (just to measure
  build time across different Yocto releases)

* still doesn't build
  http://errors.yoctoproject.org/Errors/Details/731829/

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>